version: '3.3'
services:
  postdb:
    image: mongo:${VER_MONGO}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - commentdb
          - postdb

  ui:
    build: ../src/ui
    image: ${USER_NAME}/ui:logging
    ports:
      - ${UI_PORT}/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
        
  post:
    build: ../src/post-py
    image: ${USER_NAME}/post:logging
    networks:
      - front_net
      - back_net
    environment:
      - POST_DATABASE_HOST=postdb
      - POST_DATABASE=posts
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - postdb
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    build: ../src/comment
    image: ${USER_NAME}/comment:logging
    networks:
      - front_net
      - back_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  prometheus:
    image: ${USER_NAME}/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - front_net
      - back_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net
      - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
