---
apiVersion: v1
kind: Service
metadata:
  name: commentdb
  labels:
    app: reddit
    component: mongo
    commentdb: "true"
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: reddit
    component: mongo
    commentdb: "true"
